### ISSUE TITLE
Deprecate rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#2123]
- [x] `declaration-block-properties-order` ([ref](https://github.com/stylelint/stylelint/issues/2035))
- [x] `selector-no-empty` ([ref](https://github.com/stylelint/stylelint/issues/2073))
- [x] `media-feature-no-missing-punctuation` ([ref](https://github.com/stylelint/stylelint/issues/2075))
- [x] `declaration-block-no-ignored-properties` ([ref](https://github.com/stylelint/stylelint/issues/2077))
- [x] `block-no-single-line` ([ref](https://github.com/stylelint/stylelint/issues/2125)) - inc. adding FAQ entry about disallowing empty line.
- [x] `no-browser-hacks` ([ref](https://github.com/stylelint/stylelint/issues/2222)) 
- [x] `no-indistinguishable-colors` ([ref](https://github.com/stylelint/stylelint/issues/2222)) 
- [x] `no-unsupported-browser-features` ([ref](https://github.com/stylelint/stylelint/issues/2222)) 
- [x] `stylelint-disable-reason`  ([ref](https://github.com/stylelint/stylelint/issues/2227)) 
- [x] `custom-property-no-outside-root` ([ref](https://github.com/stylelint/stylelint/issues/2226))
- [x] `root-no-standard-properties` ([ref](https://github.com/stylelint/stylelint/issues/2226))
- [x] `selector-root-no-composition` ([ref](https://github.com/stylelint/stylelint/issues/2226))
- [x] `time-no-imperceptible`  ([ref](https://github.com/stylelint/stylelint/issues/2249))

**Comment by m-allanson** [comment]
I can probably do this in the next few days, using the pattern set in [#801](https://github.com/stylelint/stylelint/pull/801/files). See below for a suggested set of deprecation messages for these rules.

# declaration-block-properties-order

**Documentation message**
Deprecated: use the community [`stylelint-order`](https://github.com/hudochenkov/stylelint-order) plugin pack instead. 

**Linter warning message**
declaration-block-properties-order has been deprecated and in 8.0 will be removed. Use the community stylelint-order plugin pack instead.


# selector-no-empty

**Documentation message**
Deprecated: this rule is outside the scope of stylelint's functionality. See [this comment](https://github.com/stylelint/stylelint/issues/2047#issuecomment-261382105) for details. 

**Linter warning message**
selector-no-empty has been deprecated and in 8.0 will be removed.


# media-feature-no-missing-punctuation

**Documentation message**
Deprecated: this rule is outside the scope of stylelint's functionality. See [this comment](https://github.com/stylelint/stylelint/issues/2047#issuecomment-261382105) for details. 

**Linter warning message**
media-feature-no-missing-punctuation has been deprecated and in 8.0 will be removed. 


# declaration-block-no-ignored-properties

**Documentation message**
Deprecated: this rule is outside the scope of stylelint's functionality. See [this comment](https://github.com/stylelint/stylelint/issues/2047#issuecomment-261382105) for details. 

**Linter warning message**
declaration-block-no-ignored-properties has been deprecated and in 8.0 will be removed. 


# block-no-single-line

**Documentation message**
Deprecated: Instead use the [block-opening-brace-newline-after]() and [block-closing-brace-newline-before]() rules with the option `"always"`. See [the FAQs for an example](#).

**Linter warning message**
block-no-single-line has been deprecated and in 8.0 will be removed. Instead use block-opening-brace-newline-after and block-closing-brace-newline-before with the "always" option.

**Comment by jeddy3** [comment]
> I can probably do this in the next few days,

That's awesome!

Leading up to version `7.0.0` we drip-fed deprecations across a few minor releases, which led to people putting out new releases of their configs on each occasion to get rid of deprecation warnings. This time around I think we should strive to get the rule deprecation _and [option deprecations](https://github.com/stylelint/stylelint/issues/1663)_ into one minor release. As such, I suggest we create a `deprecations` branch to contain this work (by PRing into it) and only merge into `master` once https://github.com/stylelint/stylelint/issues/2079 and https://github.com/stylelint/stylelint/issues/1663 are resolved.

> using the pattern set in #801 (but I will add tests)

It's tricky to maintain the current tests as the `testRule` function expects _one_ or _no_ warnings, and introducing a deprecation warning throws these off by one. In the past, we've simply _replaced_ the `testRule` tests with a [single deprecation warning test](https://github.com/stylelint/stylelint/pull/1353/files#diff-6aaeb804dd10043b7ca1779041964d95R218). I think that'll be fine in these instances too.

> See below for a suggested set of deprecation messages for these rules.

These LGTM. We can also finesse them per PR when we see them in situ.

**Comment by m-allanson** [comment]
I'm wondering if we should leave these rules in place for v8 (with deprecation notices) and then remove them in v9?

**Comment by jeddy3** [comment]
> I'm wondering if we should leave these rules in place for stylelint v8 (with deprecation notices) and then remove them in v9?

Let's deprecate in a point release and remove in `8.0.0` otherwise we're going have untested and deprecated code sticking around for at least a few months.

**Comment by m-allanson** [comment]
>Let's deprecate in a point release and remove in 8.0.0 otherwise we're going have untested and deprecated code sticking around for at least a few months.

That sounds fine to me, although it's worth noting that in the above PR almost all the existing tests have remained in place. Maybe it's a question we can revisit once the other deprecation PRs have landed in the `deprecations` branch.

**Comment by jeddy3** [comment]
> That sounds fine to me, although it's worth noting that in the above PR almost all the existing tests have remained in place.

I just saw that. Excellent stuff :)

**Comment by hudochenkov** [comment]
Last batch was deprecated in #2285

**Comment by jeddy3** [comment]
How do we all feel about putting out these deprecations in the next release?

**Comment by davidtheclark** [comment]
@jeddy3 Yes, we should get them out as soon as possible.

**Comment by hudochenkov** [comment]
Sounds good to me.

**Comment by jeddy3** [comment]
Merged into `master`.

**Comment by sinedied** [comment]
Is there any way to disable the deprecation warnings?

Until a proper replacement solution for `'no-unsupported-browser-features'` is done, I plan to stick with the `7.x` branch but it's annoying to have that warning during the transition.

**Comment by Slamdunk** [comment]
Hi, a rule like `no-browser-hacks` has been deprecated indicating that a plugin better fits its purpose, but I can't see any migration guide. Are there any plan to create one?

**Comment by evilebottnawi** [comment]
@Slamdunk you can be champion of this plugin :+1:

**Comment by jeddy3** [comment]
@Slamdunk There's [a guide to writing plugins](https://stylelint.io/developer-guide/plugins/) within the developer guide. As per the [CHANGELOG](https://stylelint.io/CHANGELOG/#780), "we encourage users to create and help maintain plugins for these rules".

As @evilebottnawi suggests, would you like to champion this plugin i.e. migrate the [existing rule code into a plugin](https://github.com/stylelint/stylelint/tree/master/lib/rules/no-browser-hacks), and release it to the community?

**Comment by Slamdunk** [comment]
I'll try. Taking into account that I've never developed in Stylelint / PostCSS / NodeJS / JavaScript, it may take a while, but I'll try.

**Comment by davidtheclark** [comment]
I sent out a tweet today prompting people to pipe up if they're interested in championing some plugins. Hopefully some people step up. 

@Slamdunk if you are interested in learning about Node and Styleling, and maintaining a relatively straightforward OSS project, I think this would be a fantastic and approachable learning experience. If you want to tackle it, I'm happy to help. Please feel free to ping or email me with any questions.

**Comment by Slamdunk** [comment]
Something like https://github.com/stylelint/stylelint/pull/2365 could be ok?
