### ISSUE TITLE
Add stylelint-disable commands support to autofix 

### ISSUE THREAD

**Issue by dan-gamble** [stylelint/stylelint#2643]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

I have a file that has `/* stylelint-disable */` `/* stylelint-enable */` wrapped around it but when using `--fix` it tries to format this file and breaks it quite bad.

> Which rule, if any, is this issue related to?

`--fix`

> What CSS is needed to reproduce this issue?

[Before](https://gist.github.com/dan-gamble/1505b0d34c7a30d3ce4c45f98530b8c6)
[After](https://gist.github.com/dan-gamble/0ae41752b61627538372c9e536084fdb)

A few of the issues:

* Double `;;` on `L38`
* No `;` on `L92` (I imagine this is where the `;;` comes from

> What stylelint configuration is needed to reproduce this issue?

[Config](https://gist.github.com/dan-gamble/30039756b9f8f8096a336b688c3e013f)

The config is pretty huge but i don't think it's the problem here

> Which version of stylelint are you using?

`7.11.0`

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI through `lint-staged`

---
- recommended config
  - [x] `declaration-block-no-duplicate-properties`
  - [x] `function-calc-no-unspaced-operator`
- standard config
  - [x] `alpha-value-notation`
  - [x] `at-rule-empty-line-before`
  - [x] `at-rule-no-vendor-prefix`
  - [x] `color-function-notation`
  - [x] `color-hex-length`
  - [x] `comment-empty-line-before`
  - [x] `comment-whitespace-inside`
  - [x] `custom-property-empty-line-before`
  - [x] `declaration-block-no-redundant-longhand-properties`
  - [x] `declaration-empty-line-before`
  - [x] `font-family-name-quotes`
  - [x] `function-name-case`
  - [x] `function-url-quotes`
  - [x] `hue-degree-notation`
  - [x] `import-notation`
  - [x] `keyframe-selector-notation`
  - [x] `length-zero-no-unit`
  - [x] `lightness-notation`
  - [x] `media-feature-range-notation`
  - [x] `media-feature-name-no-vendor-prefix`
  - [x] `property-no-vendor-prefix`
  - [x] `rule-empty-line-before`
  - [x] `selector-attribute-quotes`
  - [x] `selector-no-vendor-prefix`
  - [x] `selector-not-notation`
  - [x] `selector-pseudo-element-colon-notation`
  - [x] `selector-type-case`
  - [x] `shorthand-property-no-redundant-values`
  - [x] `value-keyword-case`
  - [x] `value-no-vendor-prefix`
- [x] `font-weight-notation`

<hr/>

- [x] `context.fix` warning
  - [x] `no-empty-source`
- [x] documentation
  - [x] rules#add-autofix
  - [x] plugins#the-anatomy-of-a-plugin
  - [x] options#fix

**Comment by evilebottnawi** [comment]
I think it is bug, should be respected by default.

**Comment by dan-gamble** [comment]
I think it also ignore `ignoreFiles` too fwiw.

**Comment by hudochenkov** [comment]
I know why `stylelint-disable` doesn't work with `--fix`. stylelint [creates `disabledRanges`](https://github.com/stylelint/stylelint/blob/ba0cf50784366a23a46398c4ff60ebb67c69a12e/lib/lintSource.js#L94) while processing style sheet. While linting, stylelint doesn't care about this ranges. They only matter, when stylelint [generates report](https://github.com/stylelint/stylelint/blob/ba0cf50784366a23a46398c4ff60ebb67c69a12e/lib/utils/report.js#L46-L57). It compares each violation and deletes violations within disabledRange.

I have no idea what to do with `--fix` and disabled ranges yet :(

**Comment by evilebottnawi** [comment]
@hudochenkov maybe create util `isStylelintDisable` and check on this before `fix` in rule?

**Comment by hudochenkov** [comment]
I came up to another problem. Disabled ranges assigned before file linted/fixed. For rules which altered lines (change empty lines, add line endings), disabled ranges might be incorrect after few fixes. Even after fixes within one rule. 

This problem affects every rule. Because if user has rule with fixing which changes lines, then every rule after this rule will have incorrect disabled ranges.

**Comment by jeddy3** [comment]
@hudochenkov Thanks for digging deeper. I suspect there are going to be some significant hurdles to overcome with this issue. As such, I suggest we push on with `8.0.0` and revisit this later. The autofix feature is marked as experimental and support for disable-ranges can be seen as a feature we'd like add, rather than a showstopping bug.

**Comment by hudochenkov** [comment]
> I suspect there are going to be some significant hurdles to overcome with this issue. As such, I suggest we push on with 8.0.0 and revisit this later. 

Agree. We should not close this issue, to not forget about this problem.

> The autofix feature is marked as experimental and support for disable-ranges can be seen as a feature we'd like add, rather than a showstopping bug.

I think we should add a note somewhere about this caveat. And suggested strategy: if user is using `stylelint --fix` and `stylelint-disable*` comments, then stylelint should be run twice. First run there might be false violations (or ignored violations), because of shifted disable ranges. On second run all results would be correct. Also worth adding, that this strategy is for correct violation reports. `--fix` will fix everything regardless disabled ranges.

**Comment by evilebottnawi** [comment]
@hudochenkov can we learn how it does `eslint`?

**Comment by hudochenkov** [comment]
@evilebottnawi of course we can. But I have a feeling that it won't help us, because of differences in architecture and approaches. Also I remember something from discussions, when we were discussing how to do autofixing. ESLint make multiple runs until everything is fixed and violations verified. And it also has some ranges for autofixing or something, that recalculated constantly. I might be mistaken about the last one.

**Comment by zkuzmic** [comment]
Any updates on this? Are you still looking for some help here?

**Comment by jeddy3** [comment]
> Are you still looking for some help here?

@zkuzmic Yes, definitely. The issue has been labeled as "help wanted" for a while, but I don't think anyone has had time to pick it up as it's quite gnarly. Is it something you can help with?

**Comment by zkuzmic** [comment]
I'd be happy to look into it at least!

**Comment by dartess** [comment]
Still relevant 😞

**Comment by stof** [comment]
In https://github.com/stylelint/stylelint/issues/4307 I suggested changing the way rules implement fixing (directly inspired by the ESLint architecture): instead of mutating the AST immediately, they would report with their fixer included, and the runner would then call that callback after checking the disabled ranges.

**Comment by jeddy3** [comment]
Since [`13.2.0`](https://stylelint.io/changelog#1320) stylelint no longer attempts to autofix sources which contain `/* stylelint-disable */` comments, making the autofix feature safer to use.

However, the underlying issue still remains.

@stof's [suggestion](https://github.com/stylelint/stylelint/issues/2643#issuecomment-535406358) sounds viable:

> instead of mutating the AST immediately, they would report with their fixer included, and the runner would then call that callback after checking the disabled ranges.

I believe the next step is a proof-of-concept (PoC) pull request showing this working with a rule or two. Once we are happy with the concept we can rally to migrate the 81 autofixable rules in stylelint to report with their fixer included.

If anyone have time, please consider [contributing this PoC](https://stylelint.io/contributing#code-contributions).

**Comment by SharakPL** [comment]
> 
> 
> Since [`13.2.0`](https://stylelint.io/changelog#1320) stylelint no longer attempts to autofix sources which contain `/* stylelint-disable */` comments, making the autofix feature safer to use.
> 
> However, the underlying issue still remains.
> 
> @stof's [suggestion](https://github.com/stylelint/stylelint/issues/2643#issuecomment-535406358) sounds viable:
> 
> > instead of mutating the AST immediately, they would report with their fixer included, and the runner would then call that callback after checking the disabled ranges.
> 
> I believe the next step is a proof-of-concept (PoC) pull request showing this working with a rule or two. Once we are happy with the concept we can rally to migrate the 81 autofixable rules in stylelint to report with their fixer included.
> 
> If anyone has time, please consider [contributing this PoC](https://stylelint.io/contributing#code-contributions).

It works but it should also respect `/* stylelint-enable */` and fix styles after this. For now it's just linting 😓

![stylelint-disable-fix-bug](https://user-images.githubusercontent.com/5007456/127312286-a46b4c3d-b545-437f-8052-515b0d429a66.gif)

**Comment by stof** [comment]
> It works but it should also fix styles before `/* stylelint-disable */` and after `/* stylelint-enable */`. For now it's just linting

Respecting these comments is precisely what requires building the new suggested API to provides a fixer callback instead of running the fixing logic directly in the rule, so that the fixing logic could be run only when rules are not ignored.

**Comment by Mouvedia** [comment]
> > instead of mutating the AST immediately, they would report with their fixer included, and the runner would then call that callback after checking the disabled ranges.
> 
> I believe the next step is a proof-of-concept (PoC) pull request showing this working with a rule or two. Once we are happy with the concept we can rally to migrate the 81 autofixable rules in stylelint to report with their fixer included.
> 
> If anyone has time, please consider [contributing this PoC](https://stylelint.io/contributing#code-contributions).

Iv refactored a rule to do just that.
@jeddy3 before I go further with the next step which is

> and the runner would then call that callback after checking the disabled ranges

is this issue ready to implement?

**Comment by Mouvedia** [comment]
@ybiquitous is this issue ready to be implemented?

**Comment by ybiquitous** [comment]
Yes, I think creating a PoC has no problem. We could evaluate this feature by the PoC.

**Comment by Miofly** [comment]
how to resolve this problem

**Comment by Mouvedia** [comment]
> Yes, I think creating a PoC has no problem. We could evaluate this feature by the PoC.

Sorry to be insistant, but I won't make the same mistake thrice.
Is this _ready to implement_?

**Comment by ybiquitous** [comment]
Yes, this is *ready to implement*. To clarify this problem, I just created a [reproducible demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgegCoUBnHATwBsYKBLTHAWihuKQCMqUC8tcB3GlBwALeCgAMABwAeAbl74ipStTqMYmdp24LhMGgHNhOMVLlYAvlhAAaEADMaVAHJIAtnEQxp7yVQB0YMTEtuAQmI4GCCAYmCgo6CAATgCuVMSJYrHx8YlUmAYiDABeMEkQDJgVKZg0OJkoOKkwWPFWmBahkBGGAGIQSW5IONEAVsThobCSIYjZCSDKVLT0DYkAjABs-gAs-uKJliAWQA):

```css
a {
	/* stylelint-disable */
	width: 0px;
	/* stylelint-enable */
	height: 0px;
/*           ^^ this "px" unit should be removed by autofix, but it isn't actually.
 */
}
```

```jsonc
// .stylelintrc.json
{
  "rules": {
    "length-zero-no-unit": true
  }
}
```

**Comment by romainmenke** [comment]
In https://github.com/stylelint/stylelint/pull/7730 and https://github.com/stylelint/stylelint/pull/7706 the general approach to fixing this issue is by adding a callback to capture the fix.

```js
callback: () => {
	ruleNode.selector = selector.replace('foo', 'bar');
},
```

Should we take this one step further and make these user configurable?

I see a parallel with `messages`.

```js
const messages = ruleMessages(ruleName, {
	rejected: (selector) => `Unexpected "foo" in selector "${selector}"`,
});

rule.messages = messages;
```

For example :

```js
const fixes = ruleFixes(ruleName, {
	foo: (search, replacement) => { ruleNode.selector = selector.replace(search, replacement) },
});

rule.fixes = fixes;
```

**Comment by Mouvedia** [comment]
The callbacks need to be on scope with the code which is run.
i.e. the captured variables or arguments passed using bind are dynamic

**Comment by romainmenke** [comment]
> The callbacks need to be on scope with the code which is run.
i.e. the captured variables or arguments passed using bind are dynamic

Updated the example above to better illustrate what I had in mind.
Indeed correct that all values need to be passed to these functions.

**Comment by Mouvedia** [comment]
I won't discuss the implementation details here but

> Should we take this one step further and make these **user configurable**?

This is really an interesting idea.
My PR takes into account #7192 and #4664 but I didn't think of that.

That's probably not achievable unless

1. the rule has only one fixer
2. the signature of the fixer is specific
i.e. not `(...args: any) => void`

If both are true it could be overwritten.
I would say that's a feature request that would need its own issue and could be achieved separately.

**Comment by Mouvedia** [comment]
We have recently merged some PRs that could be used as references if you wanted to tackle some of the rule refactors that are left to do. Just please announce it before you start working on one or several.

disclaimer: not all refactors are beginner friendly though, choose the rule carefully

**Comment by ybiquitous** [comment]
@Mouvedia For other contributors or plugin authors, can you please document the new `fix` callback here?
https://github.com/stylelint/stylelint/blob/2be707216a2a3d1061fb4048fc8e550d085f405d/docs/developer-guide/rules.md#add-autofix

**Comment by Mouvedia** [comment]
It was [already planned](https://github.com/stylelint/stylelint/issues/2643#issue-236146738) to be done after the last refactor.
Ill try to find time for it in the coming weeks.

**Comment by Mouvedia** [comment]
@romainmenke you must be more familiar with `function-calc-no-unspaced-operator` than me; can you take care of it?

**Comment by ybiquitous** [comment]
Refactoring all rules is done. ✅

**Comment by Mouvedia** [comment]
FYI

- exposition of `fixed`, `replacement` and `range` is being tracked by #4664 and #7192
- discussions regarding implementation is taking place in #7784
- configuration comments are not supported by `checkAgainstRule` (see #7903)
