### ISSUE TITLE
Add autofix to rules for parity with stylefmt

### ISSUE THREAD

**Issue by modosc** [stylelint/stylelint#2829]
> Describe the issue. Is it a bug or a feature request (new rule, new option, etc.)?

feature request: start merging in fix code from https://github.com/morishitter/stylefmt

(see also https://github.com/morishitter/stylefmt/issues/291)

the `stylefmt` repo has been very quiet for a while, the [last commit](https://github.com/morishitter/stylefmt#notice-consider-other-tools-before-adopting-stylefmt) recommends people use `stylint --fix` instead. 

i've written some fixes there and bugfixed others - there is a lot of code from this project copied there for parsing / etc so i think porting many of the rules would be straightforward. 

maybe opening a new issue up for each rule would be a start? i'm happy to help with some this, we rely on this working at my workplace. 

> Which rule, if any, is this issue related to?

none

> What CSS is needed to reproduce this issue?

none

> What stylelint configuration is needed to reproduce this issue?

none

> Which version of stylelint are you using?

current

> How are you running stylelint: CLI, PostCSS plugin, Node API?

CLI with `stylelint --config myconfig *.css`

> Does your issue relate to non-standard syntax (e.g. SCSS, nesting, etc.)?

no

> What did you expect to happen?

nothing

> What actually happened (e.g. what warnings or errors you are getting)?

nothing

---

Edit - list of rules:

- [x] [at-rule-semicolon-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/at-rule-semicolon-newline-after)
- [x] [block-closing-brace-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-closing-brace-newline-after)
- [x]  [block-closing-brace-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-closing-brace-newline-before)
- [x]  [block-opening-brace-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-newline-after) - #3441
- [x]  [block-opening-brace-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-newline-before)
- [ ] once we start fixing/changing newlines we need to revisit [this conversation](https://github.com/stylelint/stylelint/pull/2787) and add appropriate tests
- [x]  [block-opening-brace-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-space-after)
- [x]  [block-opening-brace-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-space-before)
- [x] [declaration-colon-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-colon-space-after)
- [x] [declaration-colon-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-colon-space-before)
- [x] [length-zero-no-unit](https://github.com/stylelint/stylelint/tree/master/lib/rules/length-zero-no-unit) - #2861
- [x]  [number-leading-zero](https://github.com/stylelint/stylelint/tree/master/lib/rules/number-leading-zero) - #2917
- [x] [number-no-trailing-zeros](https://github.com/stylelint/stylelint/tree/master/lib/rules/number-no-trailing-zeros) - #2947
- [x]  [selector-combinator-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-combinator-space-after)
- [x]  [selector-combinator-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-combinator-space-before)
- [ ]  [selector-list-comma-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-newline-after) - #3421
- [x]  [selector-list-comma-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-newline-before)
- [x]  [selector-list-comma-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-space-after)
- [x]  [selector-list-comma-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-space-before)
- [x]  [shorthand-property-no-redundant-values](https://github.com/stylelint/stylelint/tree/master/lib/rules/shorthand-property-no-redundant-values) - #2956
- [x]  [string-quotes](https://github.com/stylelint/stylelint/tree/master/lib/rules/string-quotes) - #2959

**Comment by modosc** [comment]
fwiw here's a list of the rules that `stylefmt` currently handles which currently can't automatically be fixed:

- [ ] [at-rule-semicolon-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/at-rule-semicolon-newline-after)
- [ ] [block-closing-brace-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-closing-brace-newline-after)
- [ ]  [block-closing-brace-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-closing-brace-newline-before)
- [ ]  [block-opening-brace-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-newline-after)
- [ ]  [block-opening-brace-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-newline-before)
- [ ]  [block-opening-brace-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-space-after)
- [ ]  [block-opening-brace-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/block-opening-brace-space-before)
- [ ] [declaration-block-properties-order](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-block-properties-order)
- [ ] [declaration-colon-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-colon-space-after)
- [ ] [declaration-colon-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/declaration-colon-space-before)
- [ ] [length-zero-no-unit](https://github.com/stylelint/stylelint/tree/master/lib/rules/length-zero-no-unit)
- [ ]  [number-leading-zero](https://github.com/stylelint/stylelint/tree/master/lib/rules/number-leading-zero)
- [ ] [number-no-trailing-zeros](https://github.com/stylelint/stylelint/tree/master/lib/rules/number-no-trailing-zeros)
- [ ]  [selector-combinator-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-combinator-space-after)
- [ ]  [selector-combinator-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-combinator-space-before)
- [ ]  [selector-list-comma-newline-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-newline-after)
- [ ]  [selector-list-comma-newline-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-newline-before)
- [ ]  [selector-list-comma-space-after](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-space-after)
- [ ]  [selector-list-comma-space-before](https://github.com/stylelint/stylelint/tree/master/lib/rules/selector-list-comma-space-before)
- [ ]  [shorthand-property-no-redundant-values](https://github.com/stylelint/stylelint/tree/master/lib/rules/shorthand-property-no-redundant-values)
- [ ]  [string-quotes](https://github.com/stylelint/stylelint/tree/master/lib/rules/string-quotes)

i'm going to open a few prs for some of these.

**Comment by jeddy3** [comment]
@modosc Thanks again for offering (and starting) to help out! And thanks for compiling the list of rules that need autofix for stylelint to achieve parity with stylefmt.

> maybe opening a new issue up for each rule would be a start? 

I'm helping triage issues in the backlog (after holidays and what not), so I'm going to be brief here and just say let's work from this issue for now, using your list above (which I've bumped into your top comment so we can see the tally in the issues list). Once we've knocked off some of the low-hanging-fruit, we can create separate issues for the remaining, more difficult, ones. Sound good?

Hopefully, I'll have time to start helping review PRs tomorrow, including [yours](https://github.com/stylelint/stylelint/pull/2861)!

**Comment by modosc** [comment]
@jeddy3 thanks! i'll pick another one this week to port. 

i think adding fix support to [whitespaceChecker](https://github.com/stylelint/stylelint/blob/master/lib/utils/whitespaceChecker.js) would handle a lot of these rules.

**Comment by BrunoFenzl** [comment]
Hi! Me and my team use stylelint extensively at work and I would like to contribute to those autofix rules. Is help wanted on this feature? If so, should I just pick one or is there some order?

cheers!

**Comment by jeddy3** [comment]
@BrunoFenzl Thanks for the offer of help! It's greatly appreciated. 

> Is help wanted on this feature?

Yes, I believe so.

>  If so, should I just pick one or is there some order?

@modosc Is doing an excellent job churning through these and is the best person to determine where help is needed. @modosc Any thoughts on if and how @BrunoFenzl can help?

**Comment by modosc** [comment]
hey @BrunoFenzl , welcome! `declaration-block-properties-order` would be a good one to pick up, i'm pretty sure all the rest will need to be handled in [whitespaceChecker](https://github.com/stylelint/stylelint/blob/master/lib/utils/whitespaceChecker.js) which i expect will be a large change.

**Comment by modosc** [comment]
@BrunoFenzl one other possible task that i don't have listed here is to verify that all the test cases from `stylefmt` are accounted for in `stylelint` (ie, is there some edge case that `stylefmt` found which we don't test for). it's probably worth opening a separate issue for this although i intended to to do this along with each of the fixes, just haven't had time yet.

**Comment by hudochenkov** [comment]
> `declaration-block-properties-order` would be a good one to pick up

This rule was deprecated long time ago and already removed in stylelint. There is [stylelint-order](https://github.com/hudochenkov/stylelint-order) for a replacement, and it has autofix.

**Comment by modosc** [comment]
@BrunoFenzl i guess it's time to tackle the whitespaceChecker stuff then

**Comment by BrunoFenzl** [comment]
@modosc, @jeddy3 Alright, I'll start with whitespaceChecker and keep you informed on progress.

**Comment by modosc** [comment]
@BrunoFenzl just checking in here - if you have anything to push remotely to share please let me know, i'd be happy to get this going.

**Comment by modosc** [comment]
i have worked on this and ran into some issues - specifically with autofixing `(newline|space)-(before|after)`. consider [this](https://github.com/stylelint/stylelint/blob/master/lib/rules/block-closing-brace-newline-after/__tests__/index.js#L83):

```
code: "a { color: pink; } b { color: red; }",
```

if we're autofixing this with `block-closing-brace-newline-after` should the space between the closing brace and `b` be preserved and if so where?

**Comment by ntwb** [comment]
In regard to `block-closing-brace-newline-after` I don't think so:
```css
a { color: pink; } b { color: red; }
```

Would become:
```css
a { color: pink; }
b { color: red; }
```

There would be no requirement for a trailing space at the end of this line would there?

```css
a { color: pink; }
```

**Comment by jeddy3** [comment]
> i have worked on this

Good stuff!

---

I think this is a tricky one as it highlights the inherent problem in _fixing_ code on a rule-by-rule basis, rather than pretty-printing an AST i.e. fixes for rules can introduce _new_ violations to rules that have already been run.

Having said that, I believe these `*-after` and `*-before` rules are only going to cause new `indentation` violations, and the `indentation` rule [is run last](https://github.com/stylelint/stylelint/blob/master/lib/rules/index.js#L338) for this very reason.

So, I'd expect `block-closing-brace-newline-after: "always"` to insert a newline char after the closing brace, producing the following:

```css
a { color: pink; }
 b { color: red; }
```

(Note the space in front of the `b` selector).

It'd then be the responsibility of the `indentation` rule to fix up that extra space.

_Inserting_ a newline address this example too:

```css
a { color: pink; }b { color: red; }
```

Alternatively, the logic could be smartened up to say: if there is whitespace before/after the brace then _replace_ that with a space/newline, otherwise _insert_ a space/newline. Which, I believe, is what @ntwb is suggesting.

Does that sound about right?

**Comment by modosc** [comment]
> (Note the space in front of the b selector).
> 
> It'd then be the responsibility of the indentation rule to fix up that extra space.

that's what i was thinking - otherwise things get too complicated. so then my next question is about ordering, how to avoid fixing one and introduction another.

or alternately these rules may actually be mutually exclusive - would there be a use case to have both enabled?

**Comment by jeddy3** [comment]
> Having said that, I believe these `*-after` and `*-before` rules are only going to cause new indentation violations, and the indentation rule is run last for this very reason.

I'm going to correct myself here as I just realised that the `*-after` and `*-before` rules are likely going to cause new `*-empty-line-before` rule violations e.g.

This config:

```
{
  "block-closing-brace-newline-after": "always",
  "rule-empty-line-before: "always"
}
```

With:

```css
a { color: pink; } b { color: red; }
```

Can anyone think of a way out of this puzzle? We could just run the `*-empty-line` rules at the end too as a workaround, like [we do](https://github.com/stylelint/stylelint/blob/master/lib/rules/index.js#L338) with `indentation`.

> so then my next question is about ordering, how to avoid fixing one and introduction another.

See above.

**Comment by modosc** [comment]
i think i'll also look at how `stylefmt` handled this - it seemed to do the right thing in my codebase.

**Comment by modosc** [comment]
well - not super helpful, `stylefmt` doesn't actually handle `block-closing-brace-space-after`.

let me keep going on this and i'll keep it the way i thought initially, ie:
```
a { color: pink; } b { color: red; }
```
becomes
```
a { color: pink; } 
 b { color: red; }
```

i'm really just trying to find a generalized solution for all the `whitespaceChecker`-based rules and i need to implement some more to figure this out.

**Comment by Arcanemagus** [comment]
I'd say issues like this are why ESLint runs multiple passes over the code until either no more issues are fixable, or it runs out of available passes (to prevent loops from conflicting rules). I'm not sure it's possible to resolve issues like this in a single pass without a _lot_ of complicated cross-logic between the rules.

**Comment by jeddy3** [comment]
> I'd say issues like this are why ESLint runs multiple passes over the code until either no more issues are fixable, or it runs out of available passes (to prevent loops from conflicting rules).

Sounds good to me. Anyone fancy implementing this?

**Comment by jeddy3** [comment]
Closing as per https://github.com/stylelint/stylelint/issues/3511#issuecomment-413500637. Let's create separate issues for each rule going forward.
