### ISSUE TITLE
Replace some of lodash functions with native ones

### ISSUE THREAD

**Issue by XhmikosR** [stylelint/stylelint#4412]
Since Node.js 8.7.0 is the minimum supported version, I think it totally makes sense to use native functions when possible.

~~Here's a branch: https://github.com/stylelint/stylelint/compare/master...XhmikosR:lodash~~

Note that I'm doing this in steps. Let me know what you think and if I should continue with this.

~~My plan is also to stop requiring lodash (even though I know it'll be cached the second time) but instead require only the needed functions later.~~

* done in #4413:

  - [x] `chain`
  - [x] `compact`
  - [x] `endsWith`
  - [x] `includes`
  - [x] `isArray`
  - [x] `isFinite`
  - [x] `isUndefined`
  - [x] `omitBy`
  - [x] `repeat`
  - [x] `startsWith`
  - [x] `sum`
  - [x] `toArray`
  - [x] `values`

* these should be sort of "easy"

  - [x] `clone`  #4442
  - [x] `forown` #4441
  - [x] `isNil` #4443
  - [x] `map` #4423 
  - [x] `omit` #4446
  - [x] `uniq` (`Set` should do the job) #4440

* Need more research:

  - [x] `find` ~~(needs further research)~~ #5359
  - [x] `findIndex` ~~(needs further research)~~
  - [x] `last` #5323
  - [x] `partial` ~~(needs further research)~~ #5334
  - [ ] `range`
  - [x] `trim` ~~#4445~~ #5360
  - [x] `isEmpty` #5324

**Comment by hudochenkov** [comment]
Good idea!

**Comment by XhmikosR** [comment]
BTW do we have a benchmark to measure the module load time? I think after I'm done with all this, there should be a small gain in load time.

The module size I doubt it will decrease a lot since many dependencies depend on the whole lodash module anyway.

**Comment by hudochenkov** [comment]
We don't have a benchmark for this. We have benchmarks for specific rules: https://stylelint.io/developer-guide/rules#improving-the-performance-of-a-rule

Also for the whole stylelint lint there are some method described https://github.com/stylelint/stylelint/issues/2454. But bear in mind, that we lazy load all rules/syntaxes and some other dependencies. So depends on configuration load time is different.

**Comment by XhmikosR** [comment]
I updated my original post with a list of the functions that we can change without reinventing the wheel

**Comment by XhmikosR** [comment]
I believe this is as good as it gets without us reinventing the wheel.

We could abstract some common code in the utils later if needed.

But what I couldn't understand and thus remove is this code: https://github.com/stylelint/stylelint/blob/master/lib/testUtils/mergeTestDescriptions.js

**Comment by m-allanson** [comment]
This might be a useful reference for anyone who'd like to work on the remaining items https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore

**Comment by ybiquitous** [comment]
> This might be a useful reference for anyone who'd like to work on the remaining items [you-dont-need/You-Dont-Need-Lodash-Underscore](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore)

I find out the repository provides an ESLint plugin [`eslint-plugin-you-dont-need-lodash-underscore`](https://www.npmjs.com/package/eslint-plugin-you-dont-need-lodash-underscore). I think the plugin should help us!

**Comment by ybiquitous** [comment]
I've updated this issue description to add the PR links for #5323 and #5324.
