### ISSUE TITLE
Refactor to remove style-search

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint#5499]
We've been gradually moving away from `style-search` in favour of using the value parser.

This is an umbrella issue to track that migration.

Rules:

- [x] `function-calc-no-unspaced-operator`
- [x] `selector-pseudo-element-colon-notation`
- [x] `value-no-vendor-prefix`

Utils:

- [x] `rangeContextNodeParser`
- [ ] `functionArgumentsSearch`

Stylistic rules and utils (no need to update as will eventually be deprecated and removed):

- `function-whitespace-after`
- `indentation`
- `max-empty-lines`
- `max-line-length`
- `no-eol-whitespace`
- `no-extra-semicolons`
- `selector-attribute-brackets-space-inside`
- `selector-list-comma-newline-after`

Utils:

- `declarationBangSpaceChecker`
- `findMediaOperator`
- `mediaFeatureColonSpaceChecker`
- `mediaQueryListCommaWhitespaceChecker`
- `selectorAttributeOperatorSpaceChecker`
- `selectorListCommaWhitespaceChecker`
- `valueListCommaWhitespaceChecker`

When adding an option or fixing a bug with one of these rules (or a rule that uses a utility using search-search), consider refactoring it to use the value parser.

Ref: https://github.com/stylelint/stylelint/pull/5496#discussion_r694494678

**Comment by ybiquitous** [comment]
Repo: https://github.com/davidtheclark/style-search

**Comment by jeddy3** [comment]
I've updated the task list above to ignore stylistic rules and utils.

It leaves us with only two rules and two utils left to migrate to a parser. 

I think `rangeContextNodeParser` is a good candidate to migrate to a future-facing parser like SWC. Having said that, all the rules can be migrated to postcss-based parsers as a stepping stone away from stylesearch.

**Comment by ybiquitous** [comment]
I try replacing `style-search` in `rangeContextNodeParser.js`, but I cannot find a parsing way for media queries including multiple operators like `@media (10em < my-max-width <= 50em)`:

https://github.com/stylelint/stylelint/blob/3de9964d38c6d9af5aa6381b0dacc6d8b035c5eb/lib/rules/rangeContextNodeParser.js#L16-L24

[`postcss-media-query-parser`](https://github.com/dryoma/postcss-media-query-parser) is not enough for the purpose. 😕 

Anyone, do you know a good way?

**Comment by jeddy3** [comment]
Can we use the value parser as a stepping stone to a parser that understands this construct?

The value parser will parse this a series of `word` nodes. We can then spot the operator `word` nodes.

**Comment by ybiquitous** [comment]
@jeddy3 Thanks, `postcss-value-parser` seems good for the purpose! I'll try it.
