### ISSUE TITLE
Create issues for TODOs and remove the ones already covered

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint#7060]
### Review

- [ ] https://github.com/search?q=repo%3Astylelint%2Fstylelint+%22TODO%22&type=code 9/15

#### Add

- [x] #7232
- [x] elirasza/stylelint-stylistic#16

#### Remove

- [x] #6615
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-specificity/index.js#L130
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-specificity/__tests__/index.mjs#L464
- [x] #6234
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-combinators/__tests__/index.mjs#L192
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-combinators/__tests__/index.mjs#L203
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-class/__tests__/index.mjs#L151
  - https://github.com/stylelint/stylelint/blob/main/lib/rules/selector-max-class/__tests__/index.mjs#L162

#### Modify

- [x] add AleshaOleg/postcss-sass#56 to
https://github.com/stylelint/stylelint/blob/f5b2dad290169b3cf459373c91e5efc67d136ec5/lib/utils/__tests__/isStandardSyntaxAtRule.test.mjs#L48

**Comment by Mouvedia** [comment]
- I missed 2 TODOs
  - https://github.com/stylelint/stylelint/blob/994112133722d7d55267a042f5c94fa8892ebed2/lib/rules/selector-max-combinators/__tests__/index.mjs#L216
  - https://github.com/stylelint/stylelint/blob/994112133722d7d55267a042f5c94fa8892ebed2/lib/rules/selector-max-combinators/__tests__/index.mjs#L225

- falls under #6930
  - `lib/formatters/__tests__/terminalLink.test.mjs`
  - `.github/dependabot.yml`

- the ones I couldn't resolve
  - [ ] `lib/rules/functionCommaSpaceChecker.js`
  - [ ] `lib/rules/color-named/index.js`
  - [ ] `lib/rules/selector-descendant-combinator-no-non-space/index.js`
  - [ ] `lib/rules/string-quotes/index.js`

**Comment by Mouvedia** [comment]
- I missed 2 TODOs
  - https://github.com/stylelint/stylelint/blob/994112133722d7d55267a042f5c94fa8892ebed2/lib/rules/selector-max-combinators/__tests__/index.mjs#L216
  - https://github.com/stylelint/stylelint/blob/994112133722d7d55267a042f5c94fa8892ebed2/lib/rules/selector-max-combinators/__tests__/index.mjs#L225

- falls under #6930
  - `lib/formatters/__tests__/terminalLink.test.mjs`
  - `.github/dependabot.yml`

- the ones I couldn't resolve
  - [ ] `lib/rules/functionCommaSpaceChecker.js`
  - [ ] `lib/rules/color-named/index.js`
  - [ ] `lib/rules/selector-descendant-combinator-no-non-space/index.js`
  - [ ] `lib/rules/string-quotes/index.js`
